# Generated by Django 6.1.2 on 2026-10-09 15:45

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Servicio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='Se genera solo a partir del título si lo dejas vacío.', max_length=180, unique=True, verbose_name='Slug (URL)')),
                ('category', models.CharField(blank=True, help_text='p. ej. Branding, Editorial, Packaging, Motion', max_length=80, verbose_name='Categoría')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año')),
                ('client', models.CharField(blank=True, max_length=120, verbose_name='Cliente')),
                ('role', models.CharField(blank=True, help_text='p. ej. Identidad visual, Dirección de arte', max_length=160, verbose_name='Mi rol')),
                ('summary', models.TextField(blank=True, max_length=300, verbose_name='Resumen corto (tarjeta)')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Descripción del proyecto')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado en portada')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Números menores aparecen primero.', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen de portada')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['sort_order', '-year', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Pie de foto')),
                ('layout', models.CharField(choices=[('full', 'Ancho completo'), ('half', 'Media columna')], default='full', max_length=10, verbose_name='Disposición')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Imagen')),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='portfolio.project')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Joswen', max_length=80, verbose_name='Nombre')),
                ('role_line', models.CharField(default='Diseñador gráfico & director de arte', max_length=120, verbose_name='Profesión (línea corta)')),
                ('location', models.CharField(blank=True, default='Remoto · Mundo', max_length=120, verbose_name='Ubicación')),
                ('hero_title', models.CharField(default='Diseño que se mueve, se siente y se recuerda.', max_length=200, verbose_name='Título principal')),
                ('hero_subtitle', models.TextField(default='Soy Joswen, diseñador gráfico. Construyo identidades, piezas editoriales y universos visuales para marcas que quieren verse como el futuro.', verbose_name='Subtítulo')),
                ('availability_text', models.CharField(blank=True, default='Disponible para nuevos proyectos', max_length=160, verbose_name='Texto de disponibilidad')),
                ('about_title', models.CharField(default='Detrás de cada pieza, una obsesión por el detalle.', max_length=200, verbose_name='Título «Sobre mí»')),
                ('about_text', wagtail.fields.RichTextField(default='<p>Trabajo en la intersección entre la estrategia de marca y la expresión visual. Cada proyecto empieza escuchando y termina en un sistema de identidad coherente, memorable y listo para vivir en cualquier soporte.</p><p>Colaboro con estudios, startups y marcas personales que buscan una dirección creativa con carácter propio.</p>', verbose_name='Texto «Sobre mí»')),
                ('clients_list', models.TextField(blank=True, default='Nébula Studio\nAtlas Coffee\nOrbita\nLumen\nPulso Records\nTerra Wines', help_text='Se muestran en la cinta animada.', verbose_name='Marcas / clientes (una por línea)')),
                ('contact_title', models.CharField(default='¿Tienes una idea? Hagámosla inolvidable.', max_length=200, verbose_name='Título de contacto')),
                ('contact_text', models.TextField(blank=True, default='Cuéntame qué necesitas y te respondo en menos de 48 horas.', verbose_name='Texto de contacto')),
                ('email', models.EmailField(default='hola@joswen.com', max_length=254, verbose_name='Email')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('behance', models.URLField(blank=True, verbose_name='Behance')),
                ('dribbble', models.URLField(blank=True, verbose_name='Dribbble')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('spline_url', models.URLField(blank=True, help_text='Pega aquí la URL «.splinecode» de una escena publicada en Spline (Export → Code → Viewer). Si se deja vacío se usa la escena 3D integrada.', verbose_name='URL de escena Spline (opcional)')),
                ('accent_color', models.CharField(default='#ff5a1f', help_text='Hexadecimal, p. ej. #ff5a1f. Elige un tono vivo y claro: el texto sobre él es azul marino.', max_length=7, verbose_name='Color de acento')),
                ('portrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Retrato / imagen «Sobre mí»')),
            ],
            options={
                'verbose_name': 'Ajustes del sitio',
                'verbose_name_plural': 'Ajustes del sitio',
            },
        ),
    ]
